// motor_mag.pro — 4极12槽表贴式永磁电机 2D 磁静力学 (Az 形式)
// 严格遵循 GetDP 官方模板 Lib_Magnetostatics_a_phi.pro 的 Magnetostatics_a 形式:
//   ∫ nu(B)·B·δB dV = ∫ Hc·δB dV (磁体) + ∫ Jz·δAz dV (槽电流)
//   B = curl(Az ẑ) = (∂Az/∂y, -∂Az/∂x)
// 非线性铁磁: Picard 迭代 (nu 取上一步 B 的磁阻率, InterpolationLinear 插值 BH 数据)
// 网格: motor_sector.geo → gmsh 生成的 motor_sector.msh

DefineConstant[
  mu0 = 4.e-7*Pi,
  // 双极性正弦相电流峰值(A), 由 Python 驱动器按转子角 δ 传入; ± 表示该槽导体电流方向
  IA  = 0.,  IAn = 0.,
  IB  = 0.,  IBn = 0.,
  IC  = 0.,  ICn = 0.,
  // 磁体: Br=1.16 T, mu_r=1.05 → Hc = Br/(mu_r*mu0) ≈ 8.80e5 A/m
  Hc_mag = 8.804e5,
  // 轴相对磁导率
  mur_shaft = 700,
  // 非线性迭代
  NL_tol_rel = 1.e-6,
  NL_iter_max = 40,
  Flag_Debug = 0,
  // 线性铁磁开关: 1=所有铁磁区用线性 Mur_Iron (解析验证用), 0=M270-35A 非线性BH
  Flag_IronLinear = 0,
  Mur_Iron  = 7000,
  Mur_Shaft = 700
];

// ============ M270-35A 铁磁 BH 数据 (Cogent 光泽钢片典型直流磁化曲线) ============
// B [T]: 0.10→2.20, H [A/m]: 36→1.6e6; nu=H/B; b2=0 处取首点斜率, 深饱和段按 mu0 外推
Function {
  b2_pts()  = {0.0, 0.01, 0.16, 0.64, 1.21, 1.69, 2.1025, 2.4025, 2.7225, 3.0625, 3.61, 4.84, 100.0};
  nu_pts()  = {360.0, 360.0, 150.0, 131.2, 172.7, 292.3, 586.2, 1419.4, 4848.5, 20000.0, 131578.9, 727272.7, 795774.7};
  nu_list() = ListAlt[b2_pts(), nu_pts()];

  iron_nu[]     = InterpolationLinear[SquNorm[$1]]{nu_list()};
  iron_dnudb2[] = dInterpolationLinear[SquNorm[$1]]{nu_list()};
}

// === HC VECTOR SECTIONS (auto-generated by run_emag_getdp.py; do not edit) ===
Function {
  hc[ Region[{magnet_N}] ] = Vector[-Hc_mag*Cos[Atan2[Y[],X[]]],
                                    -Hc_mag*Sin[Atan2[Y[],X[]]], 0. ];
  hc[ Region[{magnet_S}] ] = Vector[ Hc_mag*Cos[Atan2[Y[],X[]]],
                                     Hc_mag*Sin[Atan2[Y[],X[]]], 0. ];
}
