#!/usr/bin/env python3
"""
GetDP 电磁链路驱动器 — 12槽4极表贴式永磁电机 (PM-SPM)

链路: generate_geo.py → gmsh(-2 -format msh2) → getdp → .pos 解析 → 指标 → JSON 报告

关键约定（已与独立 FEM (fem_check.py) 交叉验证, 气隙 Bn 一致性 0.5%）:
- GetDP 4.0.0 无 Gmsh 支持 → 网格必须 -format msh2
- .pos 向量视图 VT 每单元 9 值: (Bx,By,Bz)×3节点, Bz=0, Form1P 的 B 为单元常量
  → 元素 B = (v[0], v[1]); a_map/az_slots 同为 9 值 (0,0,A)×3节点 → 节点 A = v[3p+2]
- 永磁极性: motor_mag.pro 中 N 极 = -Hc（GetDP 将非 Dof Integral 项移 RHS 带负号）
- 物理组: 1=shaft 2=rotor_iron 3=magnet_N 4=magnet_S 5=airgap
          6=SlotAp 8=SlotCn 9=SlotBp 10=SlotAn 11=SlotCp 12=SlotBn 7=stator_iron 13=Outer

输出: 无载气隙 Bn 剖面(极均值/Bg1/THD), 相 A 磁链 λa, δ 扫掠转矩 T(δ)
      (Maxwell 应力环积分, 与 T=1.5·p·λa·I·sin(δ) 公式对比)

v2 转矩裁决 (与 C++ 仲裁器 vw_arbiter 互证, 见 simulation/getdp/vw_arbiter):
- T_fem(δ=90°) = −0.93 Nm 是瞬时 Maxwell 应力 = 平均转矩 + 齿槽(+0.14, θ=0 处与
  平均反向) + 纹波; 不能与平均转矩公式直接对表。
- 平均转矩 = 共能虚功 W_int(δ) = Σ i_k λ_k = −1.5·λ₁·I·cosδ (δ 电角度),
  T_avg = p·(−dW/dδ) = p·A — 旧口径漏乘对极数 p=2 (0.51 → 1.02 Nm)。
- 三口径互证 (js峰 2e6): 斜率法 1.0104 / 幅值法 1.0220 / 公式 1.5·p·λ₁·i_pk = 1.0220
  Nm, GetDP 同恒等式 1.025 — 1.2% 内一致; λ₁(能量)=1.1295 Wb vs λm(4NcLΔA)=0.9784
  Wb, ~14% 为气隙单带采样 vs 槽窗积分的系统偏差。
- 恒等式分解: W_int = W_dl − W_nl − W_arm (纯电枢解 = -setnumber Hc_mag 0),
  叠加验证 T_pm + T_arm + T_cross = T_dl 逐位成立。
"""
import json
import math
import os
import re
import subprocess
import sys
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

# 捆绑求解器（仓库 bin/third_party），PATH 里有同名工具时优先 PATH
_REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", "..", ".."))
GMSH_BIN = os.path.join(_REPO, "bin", "third_party", "gmsh", "bin", "gmsh")
GETDP_BIN = os.path.join(_REPO, "bin", "third_party", "getdp", "bin", "getdp")
if not os.path.isfile(GMSH_BIN):
    GMSH_BIN = "gmsh"
if not os.path.isfile(GETDP_BIN):
    GETDP_BIN = "getdp"

from load_constants import merged_design, materials, physics, operating
import temp_spec

_C = materials()
MU0 = physics()["MU0"]

# 几何/绕组参数 — constants/motor_design.json 统一管理(原写死值已迁移)
P = merged_design()
assert abs(P["Br"] - _C["magnet_N35UH"]["Br_20"]) < 1e-12  # 设计与材料一致性

TAG_SLOT = {6: "SlotAp", 8: "SlotCn", 9: "SlotBp", 10: "SlotAn", 11: "SlotCp", 12: "SlotBn"}


def slot_area():
    """扇形槽截面积 (Δθ/2)(r2²−r1²)。"""
    dth = math.radians(2 * P["slot_half_deg"])
    r1, r2 = P["R_si"], P["R_si"] + P["slot_depth"]
    return 0.5 * dth * (r2 * r2 - r1 * r1)


def js_to_i(js):
    """槽电流密度(A/m²) → 相电流峰值(A): js = 2·Nc·i/A_slot (双层)。"""
    return js * slot_area() / (2 * P["Nc"])


_VT = re.compile(r"VT\(([^)]*)\)\{([^}]*)\}")


def parse_pos_vv(path):
    """解析 GetDP .pos → (coords[n,9], vals[n,9])。"""
    cs, vs = [], []
    with open(path) as f:
        for mo in _VT.finditer(f.read()):
            cs.append([float(x) for x in mo.group(1).replace(",", " ").split()])
            vs.append([float(x) for x in mo.group(2).replace(",", " ").split()])
    return np.asarray(cs), np.asarray(vs)


def parse_bmap(path):
    """b_map.pos → [cx, cy, Bx, By] 每单元一行。元素 B = (v[0], v[1])。"""
    cs, vs = parse_pos_vv(path)
    assert vs.shape[1] == 9, f"b_map 期望 9 值/单元, 得到 {vs.shape[1]}"
    cx = cs[:, 0::3].mean(axis=1)
    cy = cs[:, 1::3].mean(axis=1)
    return np.column_stack([cx, cy, vs[:, 0], vs[:, 1]])


def parse_az(path):
    """az/a_map.pos → (cx, cy, az_mean) 每单元, A 取 v[3p+2] 平均。"""
    cs, vs = parse_pos_vv(path)
    assert vs.shape[1] == 9, f"az 期望 9 值/单元, 得到 {vs.shape[1]}"
    cx = cs[:, 0::3].mean(axis=1)
    cy = cs[:, 1::3].mean(axis=1)
    az = vs[:, 2::3].mean(axis=1)
    return cx, cy, az


def write_hc_sections(wd, p, hc_scale=1.0):
    """hc 矫顽场向量场段定义 → motor_mag_data.pro 尾部 (通用参数化, 单一事实源)。

    radial:  N 极 −Hc·r̂ / S 极 +Hc·r̂ (GetDP RHS 符号约定, 与原 motor_mag.pro 一致)
    halbach: 每段平行充磁常向量, 方向角 φ_k = 2·θ_ck (理想 Halbach 2θ 旋转离散)
    hc_scale: M100 温变磁体 k(T)=1+α_Br·(T−20) (radial 经 Hc_mag setnumber 缩放,
              halbach 数值向量在此直接乘; 常温 k=1 逐位不变)
    """
    hb = int(p.get("halbach_segments", 0) or 0)
    use_hb = str(p.get("magnetization", "radial")) == "halbach" and hb > 0
    hc0 = p.get("Hc0", 8.804e5)
    lines = ["", "// === HC VECTOR SECTIONS (auto-generated by run_emag_getdp.py; do not edit) ===",
             "Function {"]
    if use_hb:
        n_poles = int(p.get("n_poles", 4))
        half = float(p.get("mag_half_deg", 33.75))
        for g in range(n_poles * hb):
            pole, k = divmod(g, hb)
            c = pole * 360.0 / n_poles
            w = 2.0 * half / hb
            theta = c - half + w * (k + 0.5)          # 段中心角(全局)
            # 理想 Halbach (p=极对数): M_r=M·cos(pθ), M_θ=-M·sin(pθ)
            #   → 直角系合成 M=Hc·(cos((p-1)θ), -sin((p-1)θ)), 向量角 φ=-(p-1)·θ
            #   (p=2 → -θ; p=1 → 0 即平行充磁 — 通用所有极数)
            #   k=p 主导 + 转子侧自屏蔽/气隙侧增强 (单边磁通效应)
            phi = math.radians(-(P["p"] - 1) * theta)
            s = -1.0
            hc_v = float(hc0) * float(hc_scale)   # M100: Hc(T) = Hc0·k(T)
            lines.append(
                f"  hc[ Region[{{magnet_hb_{g}}}] ] = "
                f"Vector[{s*hc_v:.6e}*Cos[{phi:.10f}], {s*hc_v:.6e}*Sin[{phi:.10f}], 0. ];")
            continue
    else:
        lines += [
            "  hc[ Region[{magnet_N}] ] = Vector[-Hc_mag*Cos[Atan2[Y[],X[]]],",
            "                                    -Hc_mag*Sin[Atan2[Y[],X[]]], 0. ];",
            "  hc[ Region[{magnet_S}] ] = Vector[ Hc_mag*Cos[Atan2[Y[],X[]]],",
            "                                     Hc_mag*Sin[Atan2[Y[],X[]]], 0. ];"]
    lines.append("}")
    path = os.path.join(wd, "motor_mag_data.pro")
    body = open(path, encoding="utf-8").read()
    marker = "// === HC VECTOR SECTIONS"
    if marker in body:                       # 重跑: 截断旧段, 防重复定义
        body = body[:body.index(marker)].rstrip() + "\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(body + "\n".join(lines) + "\n")
    return f"halbach({hb}seg)" if use_hb else "radial"


class ProgressReporter:
    """统一进度汇报 + 日志落盘 (商业口径: 进度/百分比/耗时/ETA 多地可读)。

    _progress.json  原子写(tmp+rename) — UI/C++/脚本统一事实源, 1s 级轮询可读
    logs/emag_*.log 全量日志追加 — 问题定位留痕
    """

    def __init__(self, wd, run_tag="emag"):
        self.wd = wd
        self.t0 = time.time()
        os.makedirs(os.path.join(wd, "logs"), exist_ok=True)
        ts = time.strftime("%Y%m%d_%H%M%S")
        self.path = os.path.join(wd, "_progress.json")
        self.logf = open(os.path.join(wd, f"logs/{run_tag}_{ts}.log"), "a",
                         encoding="utf-8")
        self.last = {}

    def step(self, stage, pct, msg=""):
        el = time.time() - self.t0
        eta = el / pct * (100.0 - pct) if pct > 1e-6 else None
        doc = {"stage": stage, "percent": round(pct, 1),
               "elapsed_s": round(el, 1),
               "eta_s": round(eta, 1) if eta is not None else None,
               "msg": msg,
               "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S")}
        tmp = self.path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(doc, f, ensure_ascii=False, indent=1)
        os.replace(tmp, self.path)                     # 原子替换
        self.logf.write(f"[{el:8.1f}s] {pct:5.1f}% {stage}  {msg}\n")
        self.logf.flush()
        self.last = doc
        return doc

    def stopped(self):
        """用户请求中止? (Stop 按钮 → C++ 写 _stop_request; 商业工具协作式取消口径)"""
        return os.path.exists(os.path.join(self.wd, "_stop_request"))

    def check_stop(self):
        """各阶段埋点调用: 请求中止 → 进度标记后退出(退出码2=用户中止, 非失败)"""
        if self.stopped():
            self.step("已中止(用户)", self.last.get("percent", 0.0), "Stop请求")
            self.finish(False, "用户中止 (Stop)")
            raise SystemExit(2)

    def finish(self, ok, summary=""):
        el = time.time() - self.t0
        self.step("完成" if ok else "失败", 100.0 if ok else self.last.get(
            "percent", 0.0), summary)
        self.logf.write(f"[{el:8.1f}s] === {'PASS' if ok else 'FAIL'}: {summary} ===\n")
        self.logf.close()


class GetDPMotorDriver:
    # 静态种子文件: 求解输入 (换 workdir 时从 HERE 复制, 并行隔离必需)
    _SEED_FILES = ("motor_mag.pro", "motor_mag_data.pro")

    def __init__(self, workdir=HERE):
        self.wd = workdir
        if os.path.abspath(workdir) != HERE:
            import shutil
            for fn in self._SEED_FILES:
                if not os.path.exists(os.path.join(workdir, fn)):
                    shutil.copy(os.path.join(HERE, fn), workdir)
        self.log = []
        # M100 温变磁体: 常温(T=20°C, k=1)时 hc_mag_t=None → 激励与既有基线逐位一致
        self.hc_mag_t = None

    def magnet_temp_state(self, p=None):
        """M100: 磁体温度激励状态 (温度来源=LPTN 磁体节点 T_Magnet_C, 单向)。

        返回 (hc_at_T, k_br, alpha_br, T); 常温 k=1 → hc=None (用 .pro 缺省,
        行为向后兼容/逐位一致)。"""
        p = p or P
        t_mag = float(p.get("T_Magnet_C", 20.0))
        alpha = float(p.get("ALPHA_BR", 0.0))
        k = temp_spec.k_br(alpha, t_mag)
        hc = temp_spec.hc_at_t(float(p["Hc0"]), alpha, t_mag) if k != 1.0 else None
        return hc, k, alpha, t_mag

    # ---------- 求解链路 ----------
    def mesh(self):
        t0 = time.time()
        # 通用参数化: P (merged_design, 含UI覆盖) → generate_geo --params
        gp = os.path.join(self.wd, "geo_params.json")
        with open(gp, "w", encoding="utf-8") as f:
            json.dump(P, f, ensure_ascii=False, indent=1)
        subprocess.run([sys.executable,
                        os.path.join(HERE, "generate_geo.py"), "--params", gp],
                       cwd=self.wd, check=True, capture_output=True)
        self.prog.check_stop()
        # M100 温变磁体: 按 T_Magnet_C 重算激励 (halbach 数值向量 / radial 存供 solve)
        hc_t, _k, _a, _t = self.magnet_temp_state(P)
        self.hc_mag_t = hc_t
        write_hc_sections(self.wd, P, hc_scale=_k)   # radial/Halbach hc 向量场段定义
        subprocess.run([GMSH_BIN, "-2", "-format", "msh2", "-o", "motor_sector.msh",
                        "motor_sector.geo"], cwd=self.wd, check=True, capture_output=True)
        self.prog.check_stop()
        self.log.append(f"mesh: {time.time() - t0:.1f}s")

    def solve(self, ia=0.0, ib=0.0, ic=0.0, linear=True, clean_res=False,
              out_bmap="b_map.pos", out_az="az_slots.pos", pm=True, hcmag=None):
        """运行 GetDP。ia/ib/ic 为槽电流密度 A/m² (Ap 带), 负带自动取负。
        pm=False 时置 Hc_mag=0 → 纯电枢场 (虚功分解 W_int = W_dl−W_nl−W_arm 用)。
        hcmag 覆盖磁体 Hc (A/m): 电磁-热耦合用, Hc(T)=Hc0·(1+αBr·(T−20)), αBr≈−0.12%/K。"""
        if clean_res and os.path.exists(os.path.join(self.wd, "motor_mag.res")):
            os.remove(os.path.join(self.wd, "motor_mag.res"))
        vals = dict(IA=ia, IAn=-ia, IB=ib, IBn=-ib, IC=ic, ICn=-ic,
                    Flag_IronLinear=1 if linear else 0, Mur_Iron=7000, Mur_Shaft=1)
        cmd = [GETDP_BIN, "motor_mag.pro", "-msh", "motor_sector.msh",
               "-solve", "Magnetostatics_a"]
        for k, v in vals.items():
            cmd += ["-setnumber", k, repr(float(v))]
        if not pm:
            cmd += ["-setnumber", "Hc_mag", "0"]
        elif hcmag is not None:
            cmd += ["-setnumber", "Hc_mag", repr(float(hcmag))]
        elif self.hc_mag_t is not None:   # M100: 磁体温度激励 Hc(T) (LPTN 单向)
            cmd += ["-setnumber", "Hc_mag", repr(float(self.hc_mag_t))]
        t0 = time.time()
        self.prog.check_stop()
        r = subprocess.run(cmd, cwd=self.wd, capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"getdp 失败:\n{r.stdout[-1500:]}\n{r.stderr[-1500:]}")
        self.log.append(f"solve(IA={ia:.3g},IB={ib:.3g}): {time.time() - t0:.1f}s")
        if out_bmap != "b_map.pos":
            os.replace(os.path.join(self.wd, "b_map.pos"), os.path.join(self.wd, out_bmap))
        if out_az != "az_slots.pos":
            os.replace(os.path.join(self.wd, "az_slots.pos"), os.path.join(self.wd, out_az))

    # ---------- 气隙采样 ----------
    def _phys_map(self):
        """groups.json: 名字→物理组编号 (generate_geo 输出, 杜绝编号硬编码)"""
        if getattr(self, "_physm", None) is None:
            with open(os.path.join(self.wd, "groups.json"), encoding="utf-8") as f:
                self._physm = json.load(f)
        return self._physm

    def _gap_tris(self, msh="motor_sector.msh"):
        """气隙带三角形单元 (节点坐标×3, tag)。"""
        from fem_check import read_msh2
        nodes, tris = read_msh2(os.path.join(self.wd, msh))
        ph_gap = self._phys_map()["airgap"]
        out = []
        for (a, b, c, phys) in tris:
            if phys != ph_gap:
                continue
            p = [nodes[a], nodes[b], nodes[c]]
            r = [math.hypot(x, y) for x, y in p]
            if P["R_rm"] + 1e-4 < sum(r) / 3 < P["R_si"] - 1e-4:
                out.append(p)
        return np.asarray(out)          # [n, 3, 2]

    def gap_circle(self, bmap_path, r_sample=None, n=1440):
        """采样圆逐点: 找包含三角 → 该单元常量 B → (θ°, Bn, Bt)。"""
        if r_sample is None:
            r_sample = P["r_gap_mid"]
        b = parse_bmap(os.path.join(self.wd, bmap_path))
        bmap = {(round(x, 6), round(y, 6)): (bx, by)
                for x, y, bx, by in b}
        tris = self._gap_tris()
        cen = tris.mean(axis=1)
        bxy = np.array([bmap[(round(c[0], 6), round(c[1], 6))] for c in cen])
        th = np.linspace(0.0, 2 * math.pi, n, endpoint=False)
        px, py = r_sample * np.cos(th), r_sample * np.sin(th)
        # 重心坐标包含测试 (向量化: n×m)
        p0 = tris[:, 0]; p1 = tris[:, 1]; p2 = tris[:, 2]
        d = ((p1[:, 1] - p2[:, 1]) * (p0[:, 0] - p2[:, 0])
             + (p2[:, 0] - p1[:, 0]) * (p0[:, 1] - p2[:, 1]))   # [m]
        X = px[:, None] - p2[None, :, 0]
        Y = py[:, None] - p2[None, :, 1]
        l1 = ((p1[:, 1] - p2[:, 1])[None, :] * X
              + (p2[:, 0] - p1[:, 0])[None, :] * Y) / d[None, :]
        l2 = ((p2[:, 1] - p0[:, 1])[None, :] * X
              + (p0[:, 0] - p2[:, 0])[None, :] * Y) / d[None, :]
        l3 = 1.0 - l1 - l2
        hit = (l1 >= -1e-9) & (l2 >= -1e-9) & (l3 >= -1e-9)
        j = np.argmax(hit, axis=1)
        ok = hit[np.arange(n), j]
        if not ok.all():
            # 回退: 未命中的采样点取最近气隙单元质心 (带边缘采样圆)
            d2 = (px[:, None] - cen[None, :, 0]) ** 2 + \
                 (py[:, None] - cen[None, :, 1]) ** 2
            miss = np.where(~ok)[0]
            j[miss] = np.argmin(d2[miss], axis=1)
        bx, by = bxy[j, 0], bxy[j, 1]
        ct, st = np.cos(th), np.sin(th)
        return np.degrees(th), bx * ct + by * st, -bx * st + by * ct

    def efficiency_map(self, js_grid=(0.0, 5e5, 1e6, 1.5e6, 2e6, 3e6, 4e6),
                       n_grid=None):
        """效率 Map (商业 Lab 模块口径): FEM 电流扫掠 T_avg(i) + 解析展开 η(n,i)。

        磁静力学 B 场与转速无关 → FEM 只做 i 扫掠 (δ=90° MTPA), 转速维解析缩放:
          P_mech = T·ω (ω=2π·n/60 机械角速度)
          P_cu   = 3·I_rms²·R_ph (R_ph 常量)
          P_fe   = (KH·f + KE·f²)·(B/B_base)²·V_fe, f = p·n/60 (铁耗常量, 热链同源)
          η      = P_mech / (P_mech + P_cu + P_fe)
        """
        from load_constants import operating
        oc = operating()
        r_ph, kh, ke = float(oc["R_ph_ohm"]), float(oc["KH_fe"]), float(oc["KE_fe"])
        f_base = float(oc["f_base_hz"])
        p = int(P["p"])
        if n_grid is None:
            n_grid = list(range(0, 6001, 500))
        # 铁耗体积 V_fe: 定子铁质量×密度反推 (50JN350 ρ=7650, 热链口径 1.7W/kg@基准)
        rho_fe, v_fe = 7650.0, 0.00077       # ≈5.9kg 定子铁 (与热链 P_fe≈4.96W 自洽)
        # ---- FEM: T_avg(js) @ δ=90° ----
        fem = []
        for js in js_grid:
            ia, ib, ic = js, -js / 2, -js / 2
            out = f"b_map_map_{js:.3e}.pos"
            self.solve(ia=ia, ib=ib, ic=ic, out_bmap=out)
            fem.append((js, js_to_i(js), abs(self.torque(out))))   # Map 用幅值(δ90°相序符号不影响效率)
            self.log.append(f"map js={js:.3e}: T={fem[-1][2]:.4f} Nm")
        # ---- 解析展开 ----
        grid = {}
        for n_rpm in n_grid:
            f_el = p * n_rpm / 60.0
            omega = 2 * math.pi * n_rpm / 60.0
            row = {}
            for js, i_pk, tq in fem:
                i_rms = i_pk / math.sqrt(2.0)
                p_mech = tq * omega
                p_cu = 3.0 * i_rms * i_rms * r_ph
                p_fe = (kh * f_el + ke * f_el * f_el) * v_fe
                denom = p_mech + p_cu + p_fe
                # i=0: 无电磁输出功率(仅齿槽), η 定义为 0 (商业 Map 惯例)
                eta = p_mech / denom if (denom > 1e-9 and i_pk > 1e-9) else 0.0
                row[f"{i_pk:.3f}"] = {"eta": round(max(eta, 0.0), 4),
                                      "T_Nm": round(tq, 4),
                                      "P_cu_W": round(p_cu, 2),
                                      "P_fe_W": round(p_fe, 2),
                                      "P_mech_W": round(p_mech, 2)}
            grid[str(n_rpm)] = row
        return {"fem_T_vs_i": [{"js_peak_Am2": js, "i_peak_A": round(ip, 3),
                                "T_avg_Nm": round(t, 4)} for js, ip, t in fem],
                "grid": grid,
                "constants": {"R_ph_ohm": r_ph, "KH_fe": kh, "KE_fe": ke,
                              "f_base_hz": f_base, "V_fe_m3": v_fe, "p_poles": p,
                              "n_rated_rpm": float(oc.get("speed_rpm", 3000)),
                              "n_max_rpm": float(n_grid[-1])}}

    def loss_metrics(self, sweep=None, bg1=None):
        """损耗 (商业 Loss 模块口径, 热链同源常量):
        P_cu = 3·I_rms²·R_ph (取扫掠最大电流点=额定);
        P_fe = (KH·f + KE·f²)·V_fe·(Bg1/B_base)², f = p·n/60 (铁耗标么展开)。
        """
        from load_constants import operating
        oc = operating()
        r_ph, kh, ke = float(oc["R_ph_ohm"]), float(oc["KH_fe"]), float(oc["KE_fe"])
        f_base, v_fe = float(oc["f_base_hz"]), float(oc.get("V_fe_m3", 0.00077))
        b_base = float(oc.get("B_base_T", 1.0))
        n_rpm = float(oc.get("speed_rpm", 3000))
        f_el = int(P["p"]) * n_rpm / 60.0
        # 额定电流: 常量 effmap_rated_js (单一事实源) → 相峰值
        i_pk = js_to_i(float(oc.get("effmap_rated_js", 2.0e6)))
        if sweep and isinstance(sweep, dict):
            i_pk = i_pk  # rows 无电流列 (delta 扫掠), 额定点以常量为准
        i_rms = i_pk / math.sqrt(2.0) if i_pk else 0.0
        p_cu = 3.0 * i_rms * i_rms * r_ph
        b_ratio = (bg1 / b_base) if (bg1 and b_base) else 1.0
        p_fe = (kh * f_base + ke * f_base * f_base) * v_fe * b_ratio * b_ratio
        return {"P_cu_W": round(p_cu, 3), "P_fe_W": round(p_fe, 3),
                "I_rms_A": round(i_rms, 3), "f_el_Hz": round(f_el, 1),
                "note": "热链LPTN同源口径; P_fe按Bg1标么缩放"}

    def demag_check(self, bmap_path="b_map_nl.pos"):
        """退磁膝点校核 (商业口径: 磁体工作点 B_par vs 膝点线 B=μ_p·μ0·H)。

        退磁曲线 B = μ_r·μ0·H + Br (沿磁化方向 m̂ 投影): H_par = (B_par − Br)/(μ_r·μ0)
        膝点 = 与磁导率线 B = μ_p·μ0·H 的交点 (KNEE_PERMEANCE=μ_p, JAC034 判据)
        risk: B_par < B_knee 的磁体单元占比; B_par_min = 最危险工作点。
        """
        from fem_check import read_msh2
        nodes, tris = read_msh2(os.path.join(self.wd, "motor_sector.msh"))
        pm = self._phys_map()
        mat = materials()["magnet_N35UH"]
        mu_p, mu_r = float(mat["KNEE_PERMEANCE"]), float(P["mur_mag"])
        br = float(P["Br"])
        h_knee = br / ((mu_p - mu_r) * MU0)          # 负值=退磁侧
        b_knee = mu_p * MU0 * h_knee
        b = parse_bmap(os.path.join(self.wd, bmap_path))
        bmap = {(round(x, 6), round(y, 6)): (bx, by) for x, y, bx, by in b}
        hb = int(P.get("halbach_segments", 0) or 0)
        use_hb = str(P.get("magnetization", "radial")) == "halbach" and hb > 0
        n_poles = int(P.get("n_poles", 4))
        half = float(P.get("mag_half_deg", 33.75))
        b_par_min, n_mag, n_risk = 1e9, 0, 0
        for (a, bb, c, phys) in tris:
            name = next((nm for nm, pid in pm.items()
                         if pid == phys and nm.startswith("magnet_")), None)
            if name is None:
                continue
            cen = ((nodes[a][0] + nodes[bb][0] + nodes[c][0]) / 3,
                   (nodes[a][1] + nodes[bb][1] + nodes[c][1]) / 3)
            v = bmap.get((round(cen[0], 6), round(cen[1], 6)))
            if v is None:
                continue
            th_c = math.atan2(cen[1], cen[0])            # 磁化方向 m̂
            if use_hb:
                g = int(name.rsplit("_", 1)[1])
                pole, k = divmod(g, hb)
                w = 2.0 * half / hb
                dd = pole * 360.0 / n_poles - half + w * (k + 0.5)
                phi = math.radians(-(P["p"] - 1) * dd)
            else:
                # radial: N 极 +r̂, S 极 -r̂ (与充磁符号一致, solve() 负 B_par 才是真退磁)
                phi = th_c if name == "magnet_N" else th_c + math.pi
            mhat = (math.cos(phi), math.sin(phi))
            b_par = v[0] * mhat[0] + v[1] * mhat[1]
            b_par_min = min(b_par_min, b_par)
            n_mag += 1
            if b_par < b_knee:
                n_risk += 1
        return {"H_knee_Am": round(h_knee, 1), "B_knee_T": round(b_knee, 4),
                "B_par_min_T": round(b_par_min, 4) if n_mag else None,
                "risk_fraction": round(n_risk / n_mag, 4) if n_mag else None,
                "n_mag_elems": n_mag}

    def no_load_metrics(self, bmap_path="b_map_nl.pos", r_sample=None):
        th, Bn, _ = self.gap_circle(bmap_path, r_sample)
        d0 = np.abs(np.mod(th + 180, 360) - 180)
        pole_mean = float(Bn[d0 < P["mag_half_deg"]].mean())
        Y = np.fft.rfft(Bn) / len(Bn)
        bg1 = float(2 * abs(Y[P["p"]]))                      # 4极基波: 空间次数 k=p
        h = 2 * np.abs(Y[1:21])                              # k=1..20
        thd = float(np.sqrt(np.sum(h ** 2) - h[P["p"] - 1] ** 2) / bg1 * 100) \
            if bg1 > 0 else 0.0
        hm, gg = P["R_rm"] - P["R_ri"], P["R_si"] - P["R_rm"]
        bg_flat = P["Br"] * hm / (hm + P["mur_mag"] * gg)    # 1D 平隙解析
        return dict(
            r_sample=r_sample or P["r_gap_mid"],
            Bg_pole_mean=round(pole_mean, 4),
            Bg1=round(bg1, 4),
            THD_pct=round(thd, 2),
            Bg1_analytic_flat=round(bg_flat, 4),
            err_vs_analytic_pct=(round((bg1 - bg_flat) / bg_flat * 100, 2)
                             if bg_flat else None),
            profile_theta=th.tolist(),
            profile_Bn=[round(float(x), 5) for x in Bn],
        )

    # ---------- 磁链 ----------
    def flux_linkage(self, az_path="az_slots_nl.pos"):
        """λm = 4·Nc·L·max_φ[A(φ) − A(φ−90°)]: 相 A 峰值磁链（4 槽双线圈边口径）。

        相 A 结构: +A 槽位于 0°/180°, −A 槽位于 90°/270° (4 极 q=1 整距, 每槽双
        层 2Nc 导体)。λa(θ) = Nc·L·2[A(θ)−A(θ+90°)+A(θ+180°)−A(θ+270°)]
        = 8NcLÂ·cos2θ, 而 ΔA = max|A(θ)−A(θ+90°)| = 2Â → λm = 4NcLΔA。
        〔v2 修正〕旧口径 2NcLΔA = 0.49 Wb 漏计相 A 的 4 槽结构 (×2 偏低)。
        C++ 仲裁器 (vw_arbiter) 能量法标定: λ₁(能量) = 1.13 Wb; 本口径 = 0.978 Wb,
        ~14% 差为 35–37mm 单带采样 vs 槽窗积分的系统偏差。
        注: 当前转子位置 N 极对准 A+ 槽(θ=0), 该处 A≡0 (极中心 B_θ=0 → A 沿 r 常
        数 = Dirichlet 值), An 槽(θ=90, S 极中心)同理 → 瞬时 λa=0 是正确物理。"""
        cx, cy, az = parse_az(os.path.join(self.wd, az_path))
        r = np.hypot(cx, cy)
        th = np.radians(np.degrees(np.arctan2(cy, cx)) % 360.0)
        band = (P["R_si"] + 0.5 * P["slot_depth"] - 1e-3 < r) \
             & (r < P["R_si"] + 0.5 * P["slot_depth"] + 1e-3)
        assert band.sum() > 50, f"槽中部 az 单元过少: {band.sum()}"
        nb = 720
        acc = np.zeros(nb); cnt = np.zeros(nb)
        ii = (th[band] / (2 * np.pi) * nb).astype(int) % nb
        np.add.at(acc, ii, az[band])
        np.add.at(cnt, ii, 1)
        m = cnt > 0
        prof = np.zeros(nb)
        prof[m] = acc[m] / cnt[m]
        # 环形补洞
        idxs = np.arange(nb)
        prof[~m] = np.interp(idxs[~m], idxs[m], prof[m], period=nb)
        shift = nb // 4                                   # 90° = 半极距
        diff = prof - np.roll(prof, shift)
        Adiff = float(np.abs(diff).max())
        lam = 4 * P["Nc"] * P["L_stack"] * Adiff
        return dict(A_diff_max=round(Adiff, 6), lambda_m_Wb=round(lam, 4),
                    Az_Ap=round(float(az[band][(np.abs(np.mod(np.degrees(th[band]),
                                30)) < 3) | (np.abs(np.mod(np.degrees(th[band]) - 180,
                                30)) < 3)].mean()), 6))

    # ---------- 转矩 ----------
    def torque(self, bmap_path, r_sample=None):
        """Maxwell 应力: T = L·r²·∮ Bn·Bt/μ0 dθ。"""
        if r_sample is None:
            r_sample = P["r_gap_mid"]
        _, Bn, Bt = self.gap_circle(bmap_path, r_sample)
        p_tan = Bn * Bt / MU0
        return float(P["L_stack"] * r_sample ** 2 * p_tan.mean() * 2 * math.pi)

    # ---------- 场能量 (共能虚功) ----------
    def _elem_table(self):
        """全部三角单元: (质心, 面积, ν)。ν 与 motor_mag.pro 线性材料一致。"""
        if getattr(self, "_elem", None) is not None:
            return self._elem
        from fem_check import read_msh2
        nodes, tris = read_msh2(os.path.join(self.wd, "motor_sector.msh"))
        # ν 按物理组名字映射 (groups.json), 与 motor_mag.pro 材料定义一致
        pm = self._phys_map()
        mur_by_name = {}
        for name, pid in pm.items():
            if name == "rotor_iron" or name == "stator_iron":
                mur_by_name[pid] = 7000.0
            elif name == "shaft":
                mur_by_name[pid] = 7000.0
            elif name.startswith("magnet_"):
                mur_by_name[pid] = 1.05
            else:
                mur_by_name[pid] = 1.0
        cen, area, nu = [], [], []
        for (a, b, c, phys) in tris:
            (xa, ya), (xb, yb), (xc, yc) = nodes[a], nodes[b], nodes[c]
            twoA = (xb - xa) * (yc - ya) - (xc - xa) * (yb - ya)
            cen.append(((xa + xb + xc) / 3, (ya + yb + yc) / 3))
            area.append(0.5 * abs(twoA))
            nu.append(1.0 / (MU0 * mur_by_name.get(phys, 1.0)))
        self._elem = (np.asarray(cen), np.asarray(area), np.asarray(nu))
        return self._elem

    def field_energy(self, bmap_path):
        """W = ∫ ½·ν·B² dA·L (线性材料磁共能, ν=1/μ 磁阻率; 全域)。"""
        cen, area, nu = self._elem_table()
        b = parse_bmap(os.path.join(self.wd, bmap_path))
        bmap = {(round(x, 6), round(y, 6)): (bx, by) for x, y, bx, by in b}
        key = [(round(c[0], 6), round(c[1], 6)) for c in cen]
        B = np.array([bmap[k] for k in key])
        b2 = (B ** 2).sum(axis=1)
        return float(0.5 * (b2 * nu * area).sum() * P["L_stack"])

    def torque_delta_sweep(self, js_peak=2.0e6,
                           deltas=(0, 30, 45, 60, 75, 90, 105, 120, 135, 150),
                           tag="dl", lam=None, w_nl=None,
                           progress=None, p0=30.0, p1=80.0, n_total=None):
        """δ 扫掠: 电流相量相对 q 轴电角度。T_fem vs T=1.5·p·λa·i·sin(δ)。

        〔v2〕共能虚功: 每点加解纯电枢场 (Hc_mag=0), W_int(δ)=W_dl−W_nl−W_arm。
        恒等式 W_int = Σ i_k·λ_k = −1.5·λ₁·I·cos δ (δ 为电角度!), 故
        平均转矩 |T_avg| = p·A (A=W_int 幅值; −dW/dθ_mech 幅值)。
        C++ 仲裁器已证: 旧口径漏乘对极数 p=2 (0.51 → 1.02 Nm)。"""
        if lam is None:
            lam = self.flux_linkage()
        if w_nl is None:
            w_nl = self.field_energy("b_map_nl.pos")
        i_pk = js_to_i(js_peak)
        rows = []
        n_tot = n_total or len(deltas)
        for i_d, d in enumerate(deltas):
            if progress:
                progress.step("转矩扫掠", p0 + (p1 - p0) * i_d / n_tot,
                              f"δ={d}° ({i_d+1}/{n_tot}, 每点2次FEM)")
                
            dr = math.radians(d)
            ia = js_peak * math.sin(dr)
            ib = js_peak * math.sin(dr - 2 * math.pi / 3)
            ic = js_peak * math.sin(dr + 2 * math.pi / 3)
            out = f"b_map_{tag}_{d}.pos"
            self.solve(ia=ia, ib=ib, ic=ic, out_bmap=out)
            arm = f"b_map_{tag}_arm_{d}.pos"
            self.solve(ia=ia, ib=ib, ic=ic, out_bmap=arm, pm=False)
            w_dl, w_arm = self.field_energy(out), self.field_energy(arm)
            w_int = w_dl - w_nl - w_arm
            rows.append(dict(delta_deg=d, T_Nm=round(self.torque(out), 4),
                             T_formula_Nm=round(1.5 * P["p"] * lam["lambda_m_Wb"]
                                                * i_pk * math.sin(dr), 4),
                             W_dl_J=round(w_dl, 6), W_arm_J=round(w_arm, 6),
                             W_int_J=round(w_int, 6)))
        res = dict(rows=rows, W_nl_J=round(w_nl, 6))
        # 最小二乘拟合 W_int = −A·cosδ → A = −Σ W·cosδ / Σ cos²δ (幅值法)
        cs = np.cos(np.radians([r_["delta_deg"] for r_ in rows]))
        ws = np.array([r_["W_int_J"] for r_ in rows])
        amp = float(-(ws * cs).sum() / (cs * cs).sum())
        res.update(W_int_amp_J=round(amp, 6),
                   T_avg_amp_Nm=round(P["p"] * amp, 4),
                   lambda1_energy_Wb=round(amp / (1.5 * i_pk), 4))
        m = {r_["delta_deg"]: r_ for r_ in rows}
        if 75 in m and 105 in m:
            # 30° 电角度窄间距中心差分 (90° 处), ×p 化机械角
            res["T_avg_slope_Nm"] = round(
                abs(P["p"] * (m[105]["W_int_J"] - m[75]["W_int_J"])
                    / math.radians(30.0)), 4)
        return res

    # ---------- 主流程 ----------
    def run_all(self, sweep=True, progress=None):
        """完整电磁链。progress: ProgressReporter 或 None (商业进度口径 20%→95%)。"""
        res = {}
        t0 = time.time()
        if progress: progress.step("空载场求解", 20, "GetDP 无载磁静力学")
        self.solve(0, 0, 0, clean_res=True, out_bmap="b_map_nl.pos",
                   out_az="az_slots_nl.pos")
        if progress: progress.step("空载指标", 26, "气隙FFT/λm/退磁膝点")
        res["no_load"] = self.no_load_metrics()
        res["demag_risk"] = self.demag_check()
        res["flux_linkage"] = self.flux_linkage()
        if sweep:
            deltas = tuple(operating().get("sweep_deltas_deg") or (0, 30, 45, 60, 75, 90, 105, 120, 135, 150))
            n_dl = len(deltas)
            res["torque_sweep"] = self.torque_delta_sweep(
                deltas=deltas,
                lam=res["flux_linkage"], w_nl=self.field_energy("b_map_nl.pos"),
                progress=progress, p0=30.0, p1=80.0, n_total=n_dl)
        res["losses"] = self.loss_metrics(res.get("torque_sweep"),
                                          res.get("no_load", {}).get("Bg1_T"))
        # M100 温变敏感度块: 线性口径解析值 (ΔBg1/Bg1 = ΔT_torque/T = α_Br·ΔT),
        # 单向披露 (温度来源=LPTN 磁体节点), 未计饱和-温度交叉项 (对标 2410.16240)
        _hc_t, _k, _a, _t = self.magnet_temp_state(P)
        _ts = temp_spec.load_temp_spec()
        _dpct = temp_spec.sensitivity_pct(_a, _ts["sensitivity_dT_K"])
        res["temp_sensitivity"] = dict(
            model=_ts["model"], disclosure=_ts["disclosure"],
            T_magnet_C=_t, alpha_br_per_K=_a, dT_K=_ts["sensitivity_dT_K"],
            bg1_change_pct=_dpct, torque_change_pct=_dpct,
            Hc_mag_at_T_Am=_hc_t if _hc_t is not None else float(P["Hc0"]),
            lambda_m_at_T_Wb=temp_spec.lambda_m_at_t(
                res.get("flux_linkage", {}).get("lambda_m_Wb", 0.0), _a, _t))
        if progress: progress.step("报告落盘", 92, "emag_report.json (含损耗)")
        res["runtime_s"] = round(time.time() - t0, 1)
        res["log"] = self.log
        with open(os.path.join(self.wd, "emag_report.json"), "w") as f:
            json.dump(res, f, ensure_ascii=False, indent=1)
        return res


if __name__ == "__main__":
    # --params <file.json>: UI 参数覆盖 (C++ adapter 通用路径; 键名同 constants/motor_design.json)
    overrides = None
    if "--params" in sys.argv:
        overrides = json.load(open(sys.argv[sys.argv.index("--params") + 1], encoding="utf-8"))
        overrides = {k: v for k, v in overrides.items() if not k.startswith("_")}
        P.update(merged_design(overrides))
        print(f"[params] UI参数覆盖: {sorted(overrides.keys())}")
    _wd = None
    if "--workdir" in sys.argv:      # 隔离工作目录 (并行批跑: 每模型独立)
        _wd = sys.argv[sys.argv.index("--workdir") + 1]
        os.makedirs(_wd, exist_ok=True)
    drv = GetDPMotorDriver(workdir=_wd) if _wd else GetDPMotorDriver()
    prog = ProgressReporter(drv.wd)
    drv.prog = prog   # Stop 协作式取消: Driver 阶段埋点经 self.prog.check_stop()
    prog.step("几何/网格", 5, "generate_geo → gmsh (UI参数实时生效)")
    drv.mesh()   # 通用参数化: 每次运行按 P 重新生成几何/网格 (偏心/Halbach/任意UI参数)
    if "--map" in sys.argv:
        prog.step("效率Map", 10, "电流扫掠FEM + 解析展开")
        em = drv.efficiency_map()
        with open(os.path.join(drv.wd, "efficiency_map.json"), "w",
                  encoding="utf-8") as f:
            json.dump(em, f, ensure_ascii=False, indent=1)
        print(f"效率 Map 已写: efficiency_map.json "
              f"({len(em['grid'])}转速×{len(em['fem_T_vs_i'])}电流点)")
        if "--map-only" in sys.argv:
            prog.finish(True, f'效率Map 13转速×7电流点'); sys.exit(0)
    prog.step("完整链启动", 15, "run_all: 无载→退磁→磁链→转矩扫掠")
    res = drv.run_all(sweep="--no-sweep" not in sys.argv, progress=prog)
    _nl = res["no_load"]
    prog.finish(True, f"Bg1={_nl['Bg1']}T THD={_nl['THD_pct']}% "
                      f"耗时{res['runtime_s']}s → emag_report.json")
    nl = res["no_load"]
    print("=== 无载 ===")
    print(f"气隙极均值 Bn = {nl['Bg_pole_mean']:.4f} T")
    print(f"基波 Bg1(k=2) = {nl['Bg1']:.4f} T  (1D 解析 {nl['Bg1_analytic_flat']:.4f}, "
          f"误差 {nl['err_vs_analytic_pct'] if nl['err_vs_analytic_pct'] is not None else '—'}%)  THD {nl['THD_pct']:.1f}%")
    fl = res["flux_linkage"]
    print(f"λm = {fl['lambda_m_Wb']:.4f} Wb  (4NcLΔA 口径; A正交差峰值 "
          f"{fl['A_diff_max']:.5f}, Ap槽 A={fl['Az_Ap']:.5f})")
    if "torque_sweep" in res:
        sw = res["torque_sweep"]
        print(f"=== T(δ)  (W_nl={sw['W_nl_J']:.4f} J) ===")
        for r_ in sw["rows"]:
            print(f"  δ={r_['delta_deg']:3d}°  T_fem={r_['T_Nm']:+9.4f}  "
                  f"T_formula={r_['T_formula_Nm']:+9.4f}  "
                  f"W_int={r_['W_int_J']:+9.5f} J")
        print("=== 平均转矩裁决 (虚功共能) ===")
        print(f"  W_int 幅值 A = {sw['W_int_amp_J']:.5f} J "
              f"(应为 −1.5·λ₁·I·cosδ 形状, W_int(90°)≈0)")
        print(f"  T_avg 斜率法 = {sw['T_avg_slope_Nm']:.4f} Nm  "
              f"幅值法 = {sw['T_avg_amp_Nm']:.4f} Nm  "
              f"(= p·(−dW/dδ), δ 为电角度 → 机械角 dθ=dδ/p)")
        print(f"  λ₁(能量法) = {sw['lambda1_energy_Wb']:.4f} Wb")
        print("  注: T_fem 为 δ=90° 瞬时 Maxwell 应力 (含齿槽+纹波), "
              "T_formula/T_avg 为平均转矩 — 三口径偏差应 <3%")
    print(f"总耗时 {res['runtime_s']}s → emag_report.json")
